### ISSUE TITLE
New card color in night mode adjustment

### ISSUE THREAD

**Issue by ghost** [calumks/anki-more-overview-stats#11]
![image](https://user-images.githubusercontent.com/13769570/74103087-1bd32000-4b41-11ea-87cd-5d6aa6ba4c59.png)
![image](https://user-images.githubusercontent.com/13769570/74103098-255c8800-4b41-11ea-8177-7dd7e122d023.png)
As evident from the image the new card color is illegible.

**Comment by teaqu** [comment]
Hello! I'm guessing you're using the [Night Mode](https://ankiweb.net/shared/info/1496166067) add-on? It appears alright for me. 

![image](https://user-images.githubusercontent.com/583418/74104846-c3a41a00-4b50-11ea-9ca5-79d243c24437.png)

Please specify your Anki version and operating system.

Thanks!

**Comment by ghost** [comment]
I'm using beta Version 2.1.20 (1fbd925f) with the native dark mode.
Windows 10
*EDIT* In case you don't know, since beta 20 Anki natively styles all dark mode elements so the add-on isn't necessary.

**Comment by teaqu** [comment]
Should be fixed now. Thanks!
