### ISSUE TITLE
Latest Update removed color of stats, all black now

### ISSUE THREAD

**Issue by mareklisek** [calumks/anki-more-overview-stats#12]
Following the most recent update the following happened: 

<img width="723" alt="Screen Shot 2020-02-11 at 11 38 55 AM" src="https://user-images.githubusercontent.com/29719476/74257677-2ae1db80-4cc3-11ea-9f8f-cbbdfa63f302.PNG">

**Comment by teaqu** [comment]
Thanks for reporting. It's fixed in the latest update.
