### ISSUE TITLE
"Due tomorrow" and "Total card" counts not working on parent decks

### ISSUE THREAD

**Issue by CubeJunkie** [calumks/anki-more-overview-stats#14]
![image](https://user-images.githubusercontent.com/69397941/89716336-73ccd100-d982-11ea-89d3-9b6c58b045eb.png)

I can see all stats correctly when I open the subdecks. But it would be great to have this info on the parent decks as a general overview.

Other than that I’m loving the addon. Keep up the good work!

**Comment by teaqu** [comment]
Should be fixed now. Thank for reporting! Sorry for delay.
