### ISSUE TITLE
“Study now” button isn't focused when using this add-on

### ISSUE THREAD

**Issue by sobjornstad** [calumks/anki-more-overview-stats#16]
I've been using this add-on for many years and have recently noticed that I can no longer press the spacebar to start studying after selecting a deck. It appears that for whatever reason, with the overview stats add-on enabled, the “Study Now” button isn't focused after opening the deck overview, whereas with it disabled, it is. Maybe part of the change to the new web views?

Hoping this is a quick fix. Let me know if there's any more information I can provide.

**Comment by omega3** [comment]
I also experience this issue.
Version ⁨2.1.51 (cf78a555)⁩
Python 3.9.10 Qt 5.15.2 PyQt 5.15.5
