### ISSUE TITLE
addons21\2116130837\__init__.py:17:confForDid is deprecated: please use 'config_dict_for_deck_id'

### ISSUE THREAD

**Issue by khonkhortisan** [calumks/anki-more-overview-stats#18]
```
addons21\2116130837\__init__.py:17:confForDid is deprecated: please use 'config_dict_for_deck_id'
```
https://github.com/teaqu/anki-more-overview-stats/blob/e3795d3d65d507739b482903f7be6075c852fa90/more_overview_stats/__init__.py#L17

 - OS: Windows 10
 - Anki Version 2.1.55 (35431c59)⁩

**Comment by teaqu** [comment]
Thanks!
