### ISSUE TITLE
anki-more-overview-stats, Feedback and Request

### ISSUE THREAD

**Issue by dedu6ka** [calumks/anki-more-overview-stats#2]
1. An add-on with the sane name already exists.  What gives ?
2. What is "Due Later" ?
3. Can you improve the old add-on by adding
    * Overdue Total
    * Due Total 
4. Replace  "Due Today" with "Due Today only"
5. Would be very helpful to add the Mouse-over for 
Custom deck and Unbury - to save unsuspected user from troubles associated with this options.

Thank you.

**Comment by teaqu** [comment]
The other add-on is made by someone else.

"Due Later" is all the cards that are due other than today. Maybe I should just do "due today" and "due total"? Might be easier to understand that way. 

I don't understand what you mean by mouse over?

Thanks for your suggestions :)

**Comment by teaqu** [comment]
Something like this might be better:

<img width="171" alt="screen shot 2017-07-24 at 10 23 51 pm" src="https://user-images.githubusercontent.com/583418/28552909-cf02b65a-70be-11e7-8dd8-6f1d526480be.png">

**Comment by dedu6ka** [comment]
On second thought, the `Due Today` is misleading; I'd modify the Anki default table 
to look like this:

- New cards Limit
- Learn, Max Reps
- Review cards Limit
- Overdue cards
- Review cards total
- Buried
- Suspended
- Unseen

What do you think ? I can supply the rationale for this upon your request. 

Mouseover. Would be nice to display the details when moving the mouse over the button.

**Comment by omega3** [comment]
Can you add due tomorrow for each deck, please?

https://anki.tenderapp.com/discussions/add-ons/31480-add-on-request-due-tomorrow-information-for-each-deck

**Comment by teaqu** [comment]
Changed due later to due tomorrow.

**Comment by teaqu** [comment]
Added to the finishded page too.
