### ISSUE TITLE
Not working in Anki 2.1 29

### ISSUE THREAD

**Issue by LoganRams** [calumks/anki-more-overview-stats#5]
I've just downloaded newest Anki beta 29 and more Overview addon but it is not working. 

![przechwytywanie](https://user-images.githubusercontent.com/34938883/34436527-ec0164dc-ec96-11e7-9917-e3d04f3fed29.PNG)

**Comment by teaqu** [comment]
Hi Logan,

It's working with me as far as I can tell. Do you get any errors? Do you have any other add-ons installed?

**Comment by teaqu** [comment]
Closing as no response & can't reproduce.
