### ISSUE TITLE
wrong Due tomorrow count

### ISSUE THREAD

**Issue by omega3** [calumks/anki-more-overview-stats#9]
It is strange but I have a wrong count in one deck. In another deck it is correct.

As you can see add-on shows 28 
https://i.imgur.com/OHcxq2r.png
while 
`prop:due=1`
for this deck shows 58.

Perhaps this is because I have not finished my repetition for today and I have some backlog from previous days. Can I provide you with further data?

**Comment by teaqu** [comment]
Added a potential fix. Let me know if it worked. Thanks :)!

**Comment by omega3** [comment]
I updated and now I get error:

```
Debug info:
Anki 2.1.12 (eef86bf3) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons possibly involved: More Overview Stats

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 363, in _onBridgeCmd
  File "aqt/deckbrowser.py", line 42, in _linkHandler
  File "aqt/deckbrowser.py", line 68, in _selDeck
  File "aqt/main.py", line 873, in onOverview
  File "aqt/main.py", line 486, in moveToState
  File "aqt/main.py", line 513, in _overviewState
  File "aqt/overview.py", line 23, in show
  File "aqt/overview.py", line 27, in refresh
  File "aqt/overview.py", line 136, in _renderPage
  File "/home/user_name/.local/share/Anki2/addons21/2116130837/__init__.py", line 19, in table
    finished = not sum(counts)
<class 'TypeError'>: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by teaqu** [comment]
How about now? We will get there. Thanks for your help! I should really add some tests to this XD.

**Comment by omega3** [comment]
No errors reported but count still not correct. 

https://imgur.com/cBpmoCe

https://imgur.com/Jsl2xqk

https://imgur.com/5B4BcWr

**Comment by teaqu** [comment]
I was including the cards that were due today in case they where not completed but I guess thats confusng.

**Comment by teaqu** [comment]
Should be correct now... I hope. I feel might need a little more work though as I was using the same db query as the stats page :/

**Comment by omega3** [comment]
Strange. But in case of one deck I have it correct in case of another deck incorrect. 

> I was including the cards that were due today in case they where not completed but I guess thats confusng.

Yes. It is confusing.

`prop:due=1`
value that I use is from Anki manual.

**Comment by teaqu** [comment]
Can you send me your deck that does not work or create one that doesn't work? Don't worry if not but would help me reproduce the issue. Thank you :).

**Comment by teaqu** [comment]
But before that try now. I've changed something else that might work using the prop:due=1
Edit: nah that didn't work...

**Comment by omega3** [comment]
My email is visible now. Send me email and I will reply with send you my deck.

One more thing: do you use regular scheduler or experimental scheduler? I switched to experimental - maybe this is why it is counted differently?

Now I changed setting to old scheduler (unchecked experimental in Preferences) and count is correct.

**Comment by teaqu** [comment]
Yeah looks like the v2 scheduler is probably the problem. A lot of changes to the cards. Sent you an email :).

**Comment by omega3** [comment]
I sent you my deck. Changing scheduler settings resets learning. You can try both schedulers.

**Comment by omega3** [comment]
Now it shows me count correctly. We may assume that v2 scheduler was the problem and that is someone experiences it, the solutions is to deactivate v2 scheduler, restart Anki and it should be ok. 

You may consider it fixed.

**Comment by teaqu** [comment]
Great :)! Let me know if any problem arises in the future and I'll devise another fix. Thanks!
